#This code generates an estimate for Pi by selecting two random numbers
#This version loads the file generated by 02_broken_writer
#IT DOES NOT WORK CORRECTLY AND DOES NOT IMPROVE RESULTS
#This is because the RNG produces the same sequence of numbers again
#as were generated in the 02_broken_writer.py code and gives no additional
#statistical power
import numpy as np
import pickle

np.random.seed(128)

ct, cti = pickle.load(open('data.pyc','rb'))

for i in range(50000):
  rnds = np.random.random(2001)
  ct += 1000
  cti += np.sum(np.sqrt(rnds[0:1000]**2+rnds[1001:2001]**2) < 1.0)

print(4.0*cti/ct)
