#This code generates an estimate for Pi by selecting two random numbers
#This version reads the pickle generated by 04_writer.py. It restarts
#the RNG using the state from the pickle. This means that it correctly
#restarts the RNG as if it had never been interrupted and generates the
#same results as the baseline case
import numpy as np
import pickle

ct, cti, state = pickle.load(open('data.pyc','rb'))

np.random.set_state(state)

for i in range(50000):
  rnds = np.random.random(2001)
  ct += 1000
  cti += np.sum(np.sqrt(rnds[0:1000]**2+rnds[1001:2001]**2) < 1.0)

print(4.0*cti/ct)
